mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapping/*.xml
  type-aliases-package: com.lucky.share.domain
hystrix:
  command:
    default:
      execution:
        isolation:
          strategy: SEMAPHORE